extren static int yy_get_next_buffer();
extren static yy_state_type yy_get_previous_state();
extren static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state );
extren static yy_state_type yy_try_NUL_trans( yy_current_state );
extren static void yyunput( int c, register char *yy_bp );
extren static void yyunput( c, yy_bp );
extren static int yyinput();
extren static int input();
extren void yyrestart( FILE *input_file );
extren void yyrestart( input_file );
extren void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer );
extren void yy_switch_to_buffer( new_buffer );
extren void yy_load_buffer_state( void );
extren void yy_load_buffer_state();
extren YY_BUFFER_STATE yy_create_buffer( FILE *file, int size );
extren YY_BUFFER_STATE yy_create_buffer( file, size );
extren void yy_delete_buffer( YY_BUFFER_STATE b );
extren void yy_delete_buffer( b );
extren void yy_init_buffer( YY_BUFFER_STATE b, FILE *file );
extren void yy_init_buffer( b, file );
extren void yy_flush_buffer( YY_BUFFER_STATE b );
extren void yy_flush_buffer( b );
extren YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size );
extren YY_BUFFER_STATE yy_scan_buffer( base, size );
extren YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str );
extren YY_BUFFER_STATE yy_scan_string( yy_str );
extren YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len );
extren YY_BUFFER_STATE yy_scan_bytes( bytes, len );
extren static void yy_push_state( int new_state );
extren static void yy_push_state( new_state );
extren static void yy_pop_state();
extren static int yy_top_state();
extren static void yy_fatal_error( yyconst char msg[] );
extren static void yy_fatal_error( msg );
extren static void yy_flex_strncpy( char *s1, yyconst char *s2, int n );
extren static void yy_flex_strncpy( s1, s2, n );
extren static int yy_flex_strlen( yyconst char *s );
extren static int yy_flex_strlen( s );
extren static void yy_flex_free( void *ptr );
extren static void yy_flex_free( ptr );
extren int yywrap();
